import fs from 'node:fs';import assert from 'node:assert/strict';
import {Box3,Vector3,Raycaster,DoubleSide} from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const buffer=fs.readFileSync('public/models/francis.glb');const {scene}=await new GLTFLoader().parseAsync(buffer.buffer.slice(buffer.byteOffset,buffer.byteOffset+buffer.byteLength),'');scene.updateMatrixWorld(true);
const meshes=[];scene.traverse(o=>{if(o.isMesh){meshes.push(o);o.material.side=DoubleSide;}});const bounds=o=>new Box3().setFromObject(o);const parts=role=>meshes.filter(o=>o.userData.chairPart===role);
for(const role of ['base','support','seat','back'])assert.equal(parts(role).length,2,`two chair ${role} parts`);
for(const base of parts('base')){const b=bounds(base),x=b.getCenter(new Vector3()).x;const nearest=role=>parts(role).find(o=>Math.abs(bounds(o).getCenter(new Vector3()).x-x)<.08);const support=bounds(nearest('support')),seat=bounds(nearest('seat')),back=bounds(nearest('back'));assert.ok(support.min.y<=b.max.y+.002,'chair body is supported by base');assert.ok(seat.min.y<=support.max.y+.002,'seat meets upholstered body');assert.ok(back.min.y<=support.max.y,'chair back meets supported body');assert.ok(back.max.y<.80,'chair upper part is lowered');assert.ok(nearest('seat').geometry.attributes.position.count>2000,'dense cushion mesh');}
const sofas=meshes.filter(o=>o.userData.category==='livingfabric'&&!o.userData.chairPart);const sofaTop=Math.max(...sofas.map(o=>bounds(o).max.y));const pillows=meshes.filter(o=>o.userData.throwPillow);assert.equal(pillows.length,3);for(const p of pillows){const b=bounds(p);assert.ok(b.min.y<.56&&b.min.y>.47,'throw cushion rests on seat');assert.ok(b.max.x>=9.72,'throw cushion leans against sofa back');assert.ok(p.geometry.attributes.position.count>2000,'filled cushion mesh');}assert.ok(meshes.some(o=>o.userData.category==='livingpillows'&&!o.userData.throwPillow),'sewn pillow edges');
const report=JSON.parse(fs.readFileSync('public/interior-refinement.json','utf8'));const walls=meshes.filter(o=>['walls','accent','featurewall'].includes(o.userData.category));const convert=p=>new Vector3(p[0],p[2],-p[1]);const ray=new Raycaster();
assert.equal(meshes.filter(o=>o.userData.wallMounted).length,report.artMounts.length);for(const art of report.artMounts){const center=convert(art.center),normal=convert(art.normal),tangent=new Vector3().crossVectors(new Vector3(0,1,0),normal);for(const u of [-.5,0,.5])for(const v of [-.5,0,.5]){const origin=center.clone().addScaledVector(tangent,(art.width+.04)*u).add(new Vector3(0,(art.height+.04)*v,0));ray.set(origin,normal.clone().negate());const hits=ray.intersectObjects(walls,false);assert.ok(hits.length&&hits[0].distance<.04,`art in ${art.room} has wall behind complete frame`);}}
assert.ok(meshes.some(o=>o.userData.woodFloor&&o.userData.category==='livingfloor'));console.log('PASS: actual chair geometry has no support gaps; lowered backs; three dense throw pillows rest on seats and reach backs; all artwork has solid walls behind full frames; separate wooden floor');
