export const finishes = {
 plaster:{name:'Warm plaster',color:'#d4d0c5',roughness:.92,texture:'plastered_wall',scale:1},
 chalk:{name:'Chalk white',color:'#edece5',roughness:.88},
 sand:{name:'Sandstone',color:'#bcb19b',roughness:.9,texture:'plastered_wall',scale:1},
 oak:{name:'Natural oak',color:'#ffffff',roughness:.65,texture:'oak_veneer_01',scale:1},
 walnut:{name:'Smoked oak',color:'#74604c',roughness:.7,texture:'oak_veneer_01',scale:1},
 marble:{name:'White veined marble',color:'#ffffff',roughness:.24,texture:'Marble012',scale:.45},
 stone:{name:'Warm stone',color:'#c6bda8',roughness:.72,texture:'marble_01',scale:.65},
 linen:{name:'Natural linen',color:'#d3ccbc',roughness:.96,texture:'woven',scale:8},
 sage:{name:'Sage weave',color:'#76836c',roughness:.96,texture:'woven',scale:8},
 charcoal:{name:'Charcoal render',color:'#303033',roughness:.83},
 clay:{name:'Terracotta',color:'#aa7661',roughness:.9},
 oakfloor:{name:'Honey oak boards',color:'#f6e8d4',roughness:.58,texture:'oak_wood_planks',scale:.65},
 shaker:{name:'Warm white lacquer',color:'#eeeee8',roughness:.36},
 bermuda:{name:'Bermuda-inspired blue',color:'#728aa5',roughness:.4},
 navy:{name:'Deep navy weave',color:'#334b61',roughness:.92,texture:'woven',scale:8},
 rose:{name:'Dusty rose weave',color:'#b7828b',roughness:.93,texture:'woven',scale:8},
 navycabinet:{name:'Deep navy lacquer',color:'#344a60',roughness:.36},
 blackstone:{name:'Polished black stone',color:'#181b1e',roughness:.17,texture:'marble_01',scale:.7},
 blackmetal:{name:'Satin black',color:'#202327',roughness:.37,metalness:.65},
 brass:{name:'Brushed brass',color:'#b99755',roughness:.3,metalness:.86},
 chrome:{name:'Brushed chrome',color:'#bfc4c8',roughness:.23,metalness:.95},
 sagepaint:{name:'Sage green',color:'#697765',roughness:.82},
 navypaint:{name:'Midnight blue',color:'#344a60',roughness:.72},
 warmwhite:{name:'Warm ivory',color:'#e7e2d7',roughness:.83},
 lavender:{name:'Soft lavender',color:'#bcb7c4',roughness:.82},
 ivory:{name:'Ivory cotton',color:'#eee9de',roughness:.96,texture:'woven',scale:8},
 paver:{name:'Grey stone paving',color:'#d6d7d4',roughness:.9,texture:'concrete_pavement',scale:.7},
 greige:{name:'Soft greige paint',color:'#bcb5a7',roughness:.82},
 olive:{name:'Olive paint',color:'#68694e',roughness:.82},
 blushpaint:{name:'Muted blush paint',color:'#c9aaa0',roughness:.82},
 graphite:{name:'Graphite lacquer',color:'#414548',roughness:.35},
 creamcab:{name:'Cream lacquer',color:'#e3d8bc',roughness:.36},
 forestcab:{name:'Forest green lacquer',color:'#354f43',roughness:.4},
 lightoak:{name:'Pale oak',color:'#fff4df',roughness:.6,texture:'oak_veneer_01',scale:1},
 darkwood:{name:'Espresso oak',color:'#49362b',roughness:.62,texture:'oak_veneer_01',scale:1},
 paleoakfloor:{name:'Pale oak boards',color:'#ffffff',roughness:.62,texture:'oak_wood_planks',scale:.65},
 smokedfloor:{name:'Smoked oak boards',color:'#827365',roughness:.65,texture:'oak_wood_planks',scale:.65},
 silverstone:{name:'Silver veined marble',color:'#b7bec2',roughness:.28,texture:'Marble012',scale:.45},
 creamstone:{name:'Cream veined marble',color:'#eee0c7',roughness:.3,texture:'Marble012',scale:.45},
 taupefabric:{name:'Taupe weave',color:'#aaa08e',roughness:.95,texture:'woven',scale:8},
 forestfabric:{name:'Forest weave',color:'#435b4e',roughness:.95,texture:'woven',scale:8},
 silverfabric:{name:'Silver grey weave',color:'#b8bdc0',roughness:.95,texture:'woven',scale:8},
 ochrefabric:{name:'Ochre weave',color:'#b79a59',roughness:.95,texture:'woven',scale:8},
 bronze:{name:'Satin bronze',color:'#66503a',roughness:.4,metalness:.75},
 gunmetal:{name:'Gunmetal',color:'#454c52',roughness:.4,metalness:.75},
 darkpaver:{name:'Charcoal paving',color:'#777c80',roughness:.9,texture:'concrete_pavement',scale:.7},
 sandpaver:{name:'Sand paving',color:'#e5d4b9',roughness:.9,texture:'concrete_pavement',scale:.7},
 clearglass:{name:'Clear glass',color:'#cad9db',roughness:.08,opacity:.16},
 smokeglass:{name:'Smoked grey glass',color:'#667c83',roughness:.1,opacity:.28},
 bronzeglass:{name:'Bronze tinted glass',color:'#9b8063',roughness:.1,opacity:.3},
 glosswhite:{name:'Glossy porcelain white',color:'#f2eee6',roughness:.12,clearcoat:.9},
 luxoak:{name:'Warm European oak boards',color:'#e6c8a3',roughness:.46,texture:'oak_wood_planks',scale:.65},
 softupholstery:{name:'Natural soft upholstery',color:'#c3b39d',roughness:.94,texture:'curly_teddy_natural',scale:3.33},
 cottoncream:{name:'Tailored cream cotton',color:'#e0d4bf',roughness:.88,texture:'cotton_jersey',scale:3.33},
 cottonsage:{name:'Sage cotton cushions',color:'#75836d',roughness:.9,texture:'cotton_jersey',scale:3.33},
 grass:{name:'Natural grass',color:'#b8cd98',roughness:1,texture:'grass_ground',scale:.6},
 mustardboucle:{name:'Mustard bouclé',color:'#a08a3a',roughness:.97,texture:'curly_teddy_natural',scale:3.33},
 oliveboucle:{name:'Olive bouclé',color:'#7f7a45',roughness:.97,texture:'curly_teddy_natural',scale:3.33},
 rustboucle:{name:'Rust bouclé',color:'#a2603b',roughness:.97,texture:'curly_teddy_natural',scale:3.33},
 creamboucle:{name:'Cream bouclé',color:'#efe6d4',roughness:.97,texture:'curly_teddy_natural',scale:3.33},
 satinwhite:{name:'Satin warm white',color:'#f1ede4',roughness:.42},
 ceilingwhite:{name:'Matte ceiling white',color:'#f4f2ec',roughness:.95},
 whitestucco:{name:'White Wallmaster stucco',color:'#f4f1ea',roughness:.93,texture:'white_stucco',scale:.5,normal:2.4},
 ivorystucco:{name:'Ivory stucco',color:'#ece4d3',roughness:.93,texture:'white_stucco',scale:.5,normal:2.4},
 sandstucco:{name:'Savannah sand stucco',color:'#d9c7a6',roughness:.93,texture:'white_stucco',scale:.5,normal:2.4},
 greystucco:{name:'Light grey stucco',color:'#c9c8c3',roughness:.93,texture:'white_stucco',scale:.5,normal:2.4},
 charcoalstucco:{name:'Charcoal Wallmaster stucco',color:'#2a2b2d',roughness:.9,texture:'white_stucco',scale:.5,normal:2.2},
 graphitestucco:{name:'Graphite stucco',color:'#45474a',roughness:.9,texture:'white_stucco',scale:.5,normal:2.2},
 bronzestucco:{name:'Dark bronze stucco',color:'#4a3f35',roughness:.9,texture:'white_stucco',scale:.5,normal:2.2},
 matteblack:{name:'Matte black powder-coat',color:'#1a1b1d',roughness:.58,metalness:.35},
 ndarugurock:{name:'Ndarugu machine-cut, rock-faced',color:'#cbb184',roughness:.92,texture:'concrete_block_wall',scale:.5,normal:1.6},
 bluerock:{name:'Nairobi blue stone, rock-faced',color:'#8e9396',roughness:.92,texture:'concrete_block_wall',scale:.5,normal:1.6},
 ndarugudressed:{name:'Ndarugu machine-cut, dressed',color:'#d6c29c',roughness:.88,texture:'sandstone_blocks_08',scale:.333,normal:1.2},
 jujastone:{name:'Juja stone, long course',color:'#b8a382',roughness:.92,texture:'granite_wall',scale:.526,normal:1.6},
 stonecladding:{name:'Mixed stone cladding',color:'#c4b08c',roughness:.93,texture:'rough_block_wall',scale:.333,normal:1.8},
 bluecladding:{name:'Nairobi blue cladding',color:'#9a9fa2',roughness:.93,texture:'rough_block_wall',scale:.333,normal:1.8},
 precast:{name:'Precast concrete',color:'#cfccc5',roughness:.9,texture:'concrete_pavement',scale:.7},
 tankblack:{name:'Black HDPE, UV-stabilised',color:'#1c1d1f',roughness:.42},
 tankgreen:{name:'Green HDPE',color:'#2f5a3c',roughness:.42},
 tankblue:{name:'Blue HDPE',color:'#2d5d8a',roughness:.42},
 tankbeige:{name:'Beige HDPE',color:'#cdbb98',roughness:.45},
 asphalt:{name:'Asphalt',color:'#5a5c5e',roughness:.95,texture:'concrete_pavement',scale:.25},
 porcelaintile:{name:'Ivory porcelain, 600 mm',color:'#efe9df',roughness:.35,texture:'interior_tiles',scale:.39,normal:.6},
 greytile:{name:'Dove grey porcelain, 600 mm',color:'#bdbab3',roughness:.35,texture:'interior_tiles',scale:.39,normal:.6},
 sandtile:{name:'Sand porcelain, 600 mm',color:'#d8c6a6',roughness:.38,texture:'interior_tiles',scale:.39,normal:.6},
 charcoaltile:{name:'Charcoal porcelain, 600 mm',color:'#4c4e51',roughness:.32,texture:'interior_tiles',scale:.39,normal:.6},
 smokedwalnut:{name:'Smoked walnut',color:'#9c7652',roughness:.55,texture:'oak_veneer_01',scale:1}
};
export const options={walls:['chalk','plaster','sand','sage','clay','warmwhite','greige','sagepaint','navypaint','olive','blushpaint'],floor:['luxoak','marble','stone','oakfloor','oak','walnut','paleoakfloor','smokedfloor','silverstone','creamstone'],wood:['oak','walnut','chalk','charcoal','lightoak','darkwood'],fabric:['linen','sage','navy','rose','clay','charcoal','ivory','taupefabric','forestfabric','silverfabric','ochrefabric'],accent:['charcoalstucco','graphitestucco','bronzestucco','charcoal','sand','chalk','oak','clay','greige','olive','navypaint'],doors:['walnut','oak','chalk','charcoal','lightoak','darkwood','warmwhite'],cabinet:['shaker','bermuda','navycabinet','sagepaint','creamcab','forestcab','graphite','oak','darkwood'],counter:['blackstone','marble','stone','silverstone','creamstone'],hardware:['blackmetal','brass','chrome','bronze','gunmetal'],bedwall:['sagepaint','navypaint','warmwhite','lavender','greige','olive','blushpaint','chalk'],bedding:['ivory','linen','rose','sage','navy','taupefabric','silverfabric'],headboard:['linen','navy','oak','sage','rose','taupefabric','forestfabric','silverfabric','darkwood'],bedfloor:['oakfloor','marble','stone','paleoakfloor','smokedfloor','silverstone','creamstone'],roof:['blackmetal','charcoal','gunmetal','bronze'],paving:['paver','stone','darkpaver','sandpaver'],lawn:['grass'],pergolaframe:['blackmetal','gunmetal','bronze'],pergolaglass:['smokeglass','clearglass','bronzeglass'],coping:['charcoal','paver','darkpaver','sand'],featurewall:['charcoalstucco','graphitestucco','bronzestucco','charcoal','blackmetal','greige','sand','navypaint','olive'],balconyglass:['clearglass','smokeglass','bronzeglass'],balconyrail:['chrome','blackmetal','gunmetal','bronze'],livingfabric:['softupholstery','cottoncream','taupefabric','linen','silverfabric','forestfabric','navy','rose'],livingrug:['linen','ivory','taupefabric','silverfabric'],tvunit:['glosswhite','creamcab','graphite','oak','darkwood'],tvwall:['creamstone','marble','silverstone','plaster','greige'],coffeetop:['marble','creamstone','silverstone','blackstone','oak'],interiormetal:['brass','blackmetal','bronze','chrome'],curtains:['ivory','linen','taupefabric','silverfabric'],livingfloor:['luxoak','oakfloor','paleoakfloor','smokedfloor'],livingpillows:['cottonsage','cottoncream','linen','rose','navy'],diningfabric:['mustardboucle','oliveboucle','rustboucle','creamboucle','softupholstery','taupefabric'],diningwood:['smokedwalnut','walnut','darkwood','oak','lightoak'],ceiling:['ceilingwhite','chalk','warmwhite','greige','plaster'],skirting:['satinwhite','chalk','charcoal','graphite','smokedwalnut','oak'],gate:['smokedwalnut','darkwood','oak','blackmetal','gunmetal','bronze'],gateframe:['blackmetal','gunmetal','bronze'],render:['whitestucco','ivorystucco','sandstucco','greystucco','chalk','plaster'],frontdoor:['matteblack','blackmetal','gunmetal','bronze','smokedwalnut','darkwood'],frontdoorframe:['blackmetal','matteblack','gunmetal','bronze'],frontdoorhardware:['brass','blackmetal','chrome','bronze','gunmetal'],boundarywall:['ndarugurock','bluerock','ndarugudressed','jujastone','whitestucco','charcoalstucco'],boundarypillar:['stonecladding','bluecladding','ndarugurock','bluerock','charcoalstucco','whitestucco'],boundarycoping:['precast','charcoalstucco','whitestucco'],watertank:['tankblack','tankgreen','tankblue','tankbeige'],tankbase:['precast','paver','charcoalstucco'],road:['asphalt','darkpaver','paver'],tapware:['chrome','blackmetal','brass','gunmetal','bronze'],bathtile:['porcelaintile','greytile','sandtile','charcoaltile','marble','creamstone'],entrydoor:['smokedwalnut','darkwood','walnut','oak','matteblack','bronze'],steps:['darkpaver','paver','sandpaver','blackstone','creamstone','marble','charcoalstucco','precast'],porch:['luxoak','smokedfloor','paleoakfloor','oakfloor','darkpaver','paver','sandpaver','creamstone','blackstone'],stairs:['luxoak','smokedfloor','paleoakfloor','oakfloor','marble','creamstone','silverstone','blackstone','stone'],stairrail:['blackmetal','brass','bronze','gunmetal','chrome','smokedwalnut']};
export const defaults={walls:'chalk',floor:'luxoak',wood:'oak',fabric:'linen',accent:'charcoalstucco',doors:'walnut',cabinet:'shaker',counter:'blackstone',hardware:'blackmetal',bedwall:'sagepaint',bedding:'ivory',headboard:'linen',bedfloor:'oakfloor',roof:'blackmetal',paving:'paver',lawn:'grass',pergolaframe:'blackmetal',pergolaglass:'smokeglass',coping:'charcoal',featurewall:'charcoalstucco',balconyglass:'clearglass',balconyrail:'chrome',livingfabric:'softupholstery',livingrug:'linen',tvunit:'glosswhite',tvwall:'marble',coffeetop:'marble',interiormetal:'brass',curtains:'ivory',livingfloor:'luxoak',livingpillows:'cottonsage',diningfabric:'mustardboucle',diningwood:'smokedwalnut',ceiling:'ceilingwhite',skirting:'satinwhite',gate:'smokedwalnut',gateframe:'blackmetal',render:'whitestucco',frontdoor:'matteblack',frontdoorframe:'blackmetal',frontdoorhardware:'brass',boundarywall:'ndarugurock',boundarypillar:'stonecladding',boundarycoping:'precast',watertank:'tankblack',tankbase:'precast',road:'asphalt',tapware:'chrome',bathtile:'porcelaintile',entrydoor:'smokedwalnut',steps:'darkpaver',porch:'luxoak',stairs:'luxoak',stairrail:'blackmetal'};
export const groupLabels={walls:'Interior walls',floor:'Kitchen & circulation floors',wood:'Timber & joinery',fabric:'Upholstery & throws',accent:'Dark exterior stucco',doors:'Doors',cabinet:'Kitchen cabinetry',counter:'Kitchen worktops',hardware:'Kitchen hardware',bedwall:'Bedroom paneling',bedding:'Bed linen & pillows',headboard:'Headboards & bed bases',bedfloor:'Bedroom floors',roof:'Canopy & roof',paving:'Exterior paving',lawn:'Lawn',pergolaframe:'Complete pergola framing',pergolaglass:'Pergola roof & terrace glass',coping:'Parapet coping',featurewall:'Entrance feature wall',balconyglass:'Balcony & terrace glass panels',balconyrail:'Balcony & terrace posts and rails',livingfabric:'Living room upholstery',livingrug:'Living room rug',tvunit:'TV cabinet finish',tvwall:'TV feature wall',coffeetop:'Living room table tops',interiormetal:'Interior metal accents',curtains:'Curtains',livingfloor:'Living room wooden flooring',livingpillows:'Living room throw pillows',diningfabric:'Dining chair upholstery',diningwood:'Dining table & chair timber',ceiling:'Ceilings & soffits',skirting:'Skirtings',gate:'Gate & tank screen slats',gateframe:'Sliding gate frame & track',render:'White exterior stucco',frontdoor:'Side entrance door',frontdoorframe:'Side entrance door frame',frontdoorhardware:'Entrance door hardware',boundarywall:'Boundary wall stone',boundarypillar:'Boundary pillars',boundarycoping:'Boundary wall coping',watertank:'Water tank (10,000 L HDPE)',tankbase:'Water tank stand',road:'Street',tapware:'Taps & shower fittings',bathtile:'Bathroom tiles',entrydoor:'Main entrance door',steps:'Entrance steps',porch:'Entrance porch deck',stairs:'Staircase treads & landings',stairrail:'Staircase railing'};
export const palettes={
 white:{name:'Classic white kitchen',changes:{cabinet:'shaker',counter:'blackstone',hardware:'blackmetal',floor:'marble'}},
 bermuda:{name:'Bermuda blue & brass',changes:{cabinet:'bermuda',counter:'marble',hardware:'brass',floor:'oakfloor'}},
 navy:{name:'Navy kitchen & brass',changes:{cabinet:'navycabinet',counter:'marble',hardware:'brass',floor:'marble'}},
 farmhouse:{name:'Neutral farmhouse bedroom',changes:{bedwall:'warmwhite',bedding:'ivory',headboard:'linen',fabric:'linen',bedfloor:'oakfloor'}},
 sage:{name:'Sage & oak bedroom',changes:{bedwall:'sagepaint',bedding:'ivory',headboard:'oak',fabric:'sage',bedfloor:'oakfloor'}},
 blue:{name:'Navy & blush bedroom',changes:{bedwall:'navypaint',bedding:'ivory',headboard:'navy',fabric:'rose',bedfloor:'oakfloor'}},
 lavender:{name:'Soft lavender bedroom',changes:{bedwall:'lavender',bedding:'ivory',headboard:'linen',fabric:'rose',bedfloor:'oakfloor'}}
};
export function defaultDesign(){return Object.fromEntries(Object.entries(defaults).map(([group,finish])=>[group,{finish,color:finishes[finish].color,roughness:finishes[finish].roughness}]));}
export function applyPalette(value,id){if(!palettes[id])throw new Error('Unknown reference palette');const result=validateDesign(value);for(const [group,finish] of Object.entries(palettes[id].changes))result[group]={finish,color:finishes[finish].color,roughness:finishes[finish].roughness};return result;}
export function validateDesign(value){
 if(!value || typeof value!=='object' || Array.isArray(value))throw new Error('Invalid finish schedule');
 const result=defaultDesign(),legacy=['walls','floor','wood','fabric','accent','doors'];
 for(const group of Object.keys(defaults)){
  const v=value[group];if(!v&&!legacy.includes(group))continue;
  if(!v||!options[group].includes(v.finish)||!/^#[0-9a-f]{6}$/i.test(v.color)||!Number.isFinite(v.roughness)||v.roughness<.05||v.roughness>1)throw new Error('Invalid finish selection for '+group);
  result[group]={finish:v.finish,color:v.color,roughness:v.roughness};
 }
 return result;
}
// Original Blender XYZ converted to glTF Y-up: (x,z,-y).
export const rooms=[
 {id:'exterior',name:'Exterior',level:'all',subtitle:'The complete residence',position:[24,16,8],target:[5,3,-13]},
 {id:'laundry',name:'Laundry balcony',level:'all',subtitle:'Glass panel & slim metal railing',position:[7,6,-28],target:[.6,4.05,-18.77]},
 {id:'gate',name:'Arrival & sliding gate',level:'all',subtitle:'Slatted gate · press Open gate',position:[13.2,1.05,8.6],target:[13.2,.6,2.5]},
 {id:'maindoor',name:'Main entrance',level:'all',subtitle:'Fluted walnut door & brass pull',position:[3.6,1.5,-6.6],target:[6.1,1.1,-8.47]},
 {id:'frontdoor',name:'Side entrance',level:'all',subtitle:'Matte black steel & brass pull',position:[0.17,1.55,-6.4],target:[0.17,1.25,-9.3]},
 {id:'tank',name:'Water tank & boundary',level:'all',subtitle:'HDPE tank, stone walling & pillars',position:[3.5,1.6,-3.2],target:[-2.4,.9,1.2]},
 {id:'garden',name:'Garden & paving',level:'all',subtitle:'Confined lawn and stepping paths',position:[-10,15,9],target:[3,0,-3]},
 {id:'terraceoverview',name:'Terrace overview',level:'all',subtitle:'Black pergola and glass balustrades',position:[20,18,-27],target:[5,7,-13]},
 {id:'entrance',name:'Entrance feature wall',level:'all',subtitle:'Dark render & warm LED strip',position:[12,6.5,5],target:[4.8,4.5,-8]},
 {id:'living',name:'Living room',level:0,subtitle:'Ground floor',position:[8.75,1.65,-12.85],target:[7.55,1.10,-10.35]},
 {id:'tvwall',name:'Living TV wall',level:0,subtitle:'Stone, glossy cabinetry & warm lighting',position:[8.95,1.65,-11.35],target:[6.45,1.25,-11.35]},
 {id:'seating',name:'Living seating',level:0,subtitle:'Inward-facing armchairs & contemporary sofa',position:[6.95,1.60,-12.60],target:[8.65,.90,-9.2]},
 {id:'chairs',name:'Armchair detail',level:0,subtitle:'Rounded upholstery & tailored arm seams',position:[8.52,1.15,-10.90],target:[8.52,.43,-8.87]},
 {id:'gallery',name:'Living gallery',level:0,subtitle:'Art, warm accents & seating',position:[7.05,1.55,-11.95],target:[10.30,1.72,-11.25]},
 {id:'kitchen',name:'Kitchen & dining',level:0,subtitle:'Ground floor',position:[5.8,1.65,-16.5],target:[3.5,1.25,-18.3]},
 {id:'dining',name:'Dining room',level:0,subtitle:'Walnut slatted table, bouclé chairs & plaster pendants',position:[7.75,1.70,-15.25],target:[9.30,.80,-16.95]},
 {id:'guest',name:'Guest bedroom',level:0,subtitle:'Ground floor',position:[1.25,1.65,-18.25],target:[-.6,.85,-17]},
 {id:'primary',name:'Primary suite',level:1,subtitle:'First floor',position:[8.8,4.8,-12.8],target:[7.4,4,-11.4]},
 {id:'bed1',name:'Bedroom one',level:1,subtitle:'First floor',position:[3.8,4.8,-18.2],target:[5,4,-17.2]},
 {id:'bed2',name:'Bedroom two',level:1,subtitle:'First floor',position:[1.4,4.8,-12.5],target:[0,4,-11.2]},
 {id:'pergola',name:'Pergola & glass terrace',level:2,subtitle:'Roof level',position:[16,11,-2],target:[8.6,8,-11.4]},
 {id:'terrace',name:'Terrace lounge',level:2,subtitle:'Roof level',position:[7.2,7.8,-16.2],target:[9,7,-18]},
 {id:'roofdining',name:'Terrace dining',level:2,subtitle:'Walnut slatted table & bouclé barrel chairs',position:[5.5,7.8,-18],target:[3.6,7,-16.8]}
];
